require("config.options")
require("config.keybinds")

require("plugins.deps")
require("plugins.colorscheme")
require("plugins.lsp")
require("plugins.devicons")
require("plugins.treesitter")
require("plugins.fzf-lua")
require("plugins.leap")
require("plugins.lazygit")
require("plugins.oil")
require("plugins.lualine")
require("plugins.blink")
